/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-09-14 16:16:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class goal_002dsetup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-BR\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>FitNutri AI - Configuração de Metas</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        tailwind.config = {\r\n");
      out.write("            theme: {\r\n");
      out.write("                extend: {\r\n");
      out.write("                    colors: {\r\n");
      out.write("                        primary: '#6366F1', // Indigo\r\n");
      out.write("                        secondary: '#4F46E5', // Indigo escuro\r\n");
      out.write("                        accent: '#8B5CF6', // Roxo\r\n");
      out.write("                        success: '#10B981', // Verde\r\n");
      out.write("                        warning: '#F59E0B', // Amarelo\r\n");
      out.write("                        danger: '#EF4444', // Vermelho\r\n");
      out.write("                        neutral: '#F8FAFC', // Cinza muito claro\r\n");
      out.write("                        dark: '#1E293B' // Azul escuro\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-white\">\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"bg-white shadow-lg fixed w-full top-0 z-50\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"flex justify-between items-center h-16\">\r\n");
      out.write("                <div class=\"flex items-center\">\r\n");
      out.write("                    <div class=\"flex-shrink-0\">\r\n");
      out.write("                        <a href=\"index.html\" class=\"text-2xl font-bold text-primary hover:text-secondary transition-colors\">\r\n");
      out.write("                            💪 FitNutri AI\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"hidden md:block\">\r\n");
      out.write("                    <div class=\"ml-10 flex items-baseline space-x-4\">\r\n");
      out.write("                        <a href=\"index.html\" class=\"nav-link text-dark hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">Início</a>\r\n");
      out.write("                        <a href=\"goal-setup.html\" class=\"nav-link text-dark hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">Metas</a>\r\n");
      out.write("                        <a href=\"nutrition.html\" class=\"nav-link text-dark hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">Nutrição</a>\r\n");
      out.write("                        <a href=\"activity.html\" class=\"nav-link text-dark hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">Atividades</a>\r\n");
      out.write("                        <a href=\"balance.html\" class=\"nav-link text-dark hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">Balanço</a>\r\n");
      out.write("                        <a href=\"ai-recommendations.html\" class=\"nav-link text-dark hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">IA Coach</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"md:hidden\">\r\n");
      out.write("                    <button id=\"mobile-menu-btn\" class=\"text-dark hover:text-primary\">\r\n");
      out.write("                        <svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Mobile menu -->\r\n");
      out.write("        <div id=\"mobile-menu\" class=\"md:hidden hidden\">\r\n");
      out.write("            <div class=\"px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-white shadow-lg\">\r\n");
      out.write("                <a href=\"index.html\" class=\"nav-link block text-dark hover:text-primary px-3 py-2 rounded-md text-base font-medium w-full text-left\">Início</a>\r\n");
      out.write("                <a href=\"goal-setup.html\" class=\"nav-link block text-dark hover:text-primary px-3 py-2 rounded-md text-base font-medium w-full text-left\">Metas</a>\r\n");
      out.write("                <a href=\"nutrition.html\" class=\"nav-link block text-dark hover:text-primary px-3 py-2 rounded-md text-base font-medium w-full text-left\">Nutrição</a>\r\n");
      out.write("                <a href=\"activity.html\" class=\"nav-link block text-dark hover:text-primary px-3 py-2 rounded-md text-base font-medium w-full text-left\">Atividades</a>\r\n");
      out.write("                <a href=\"balance.html\" class=\"nav-link block text-dark hover:text-primary px-3 py-2 rounded-md text-base font-medium w-full text-left\">Balanço</a>\r\n");
      out.write("                <a href=\"ai-recommendations.html\" class=\"nav-link block text-dark hover:text-primary px-3 py-2 rounded-md text-base font-medium w-full text-left\">IA Coach</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Goal Setup Page -->\r\n");
      out.write("    <div id=\"goal-setup-page\" class=\"page active pt-16\">\r\n");
      out.write("        <div class=\"min-h-screen bg-neutral\">\r\n");
      out.write("            <div class=\"max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-20\">\r\n");
      out.write("                <div class=\"text-center mb-12\">\r\n");
      out.write("                    <h1 class=\"text-3xl md:text-4xl font-bold text-dark mb-4\">🎯 Configuração de Metas</h1>\r\n");
      out.write("                    <p class=\"text-lg text-gray-600\">Servlet de definição de objetivos personalizados</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"bg-white rounded-2xl p-8 card-shadow\">\r\n");
      out.write("                    <div class=\"grid lg:grid-cols-2 gap-8\">\r\n");
      out.write("                        <!-- Personal Info -->\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h3 class=\"text-xl font-semibold text-dark mb-6\">Informações Pessoais</h3>\r\n");
      out.write("                            <div class=\"space-y-4\">\r\n");
      out.write("                                <div class=\"grid grid-cols-2 gap-4\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label class=\"block text-sm font-medium text-dark mb-2\">Idade</label>\r\n");
      out.write("                                        <input type=\"number\" id=\"age\" value=\"30\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label class=\"block text-sm font-medium text-dark mb-2\">Sexo</label>\r\n");
      out.write("                                        <select id=\"gender\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent\">\r\n");
      out.write("                                            <option value=\"male\">Masculino</option>\r\n");
      out.write("                                            <option value=\"female\">Feminino</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"grid grid-cols-2 gap-4\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label class=\"block text-sm font-medium text-dark mb-2\">Peso Atual (kg)</label>\r\n");
      out.write("                                        <input type=\"number\" id=\"current-weight\" value=\"75\" step=\"0.1\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label class=\"block text-sm font-medium text-dark mb-2\">Altura (cm)</label>\r\n");
      out.write("                                        <input type=\"number\" id=\"height\" value=\"175\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <label class=\"block text-sm font-medium text-dark mb-2\">Nível de Atividade</label>\r\n");
      out.write("                                    <select id=\"activity-level\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent\">\r\n");
      out.write("                                        <option value=\"1.2\">Sedentário (pouco ou nenhum exercício)</option>\r\n");
      out.write("                                        <option value=\"1.375\">Levemente ativo (exercício leve 1-3 dias/semana)</option>\r\n");
      out.write("                                        <option value=\"1.55\" selected>Moderadamente ativo (exercício moderado 3-5 dias/semana)</option>\r\n");
      out.write("                                        <option value=\"1.725\">Muito ativo (exercício pesado 6-7 dias/semana)</option>\r\n");
      out.write("                                        <option value=\"1.9\">Extremamente ativo (exercício muito pesado, trabalho físico)</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Goals -->\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h3 class=\"text-xl font-semibold text-dark mb-6\">Objetivos</h3>\r\n");
      out.write("                            <div class=\"space-y-4\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <label class=\"block text-sm font-medium text-dark mb-2\">Meta Principal</label>\r\n");
      out.write("                                    <div class=\"space-y-2\">\r\n");
      out.write("                                        <label class=\"flex items-center p-3 border rounded-lg cursor-pointer hover:bg-gray-50\">\r\n");
      out.write("                                            <input type=\"radio\" name=\"goal\" value=\"weight-loss\" class=\"mr-3\" checked>\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <div class=\"font-medium\">🔥 Perder Peso</div>\r\n");
      out.write("                                                <div class=\"text-sm text-gray-600\">Déficit calórico para queima de gordura</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label class=\"flex items-center p-3 border rounded-lg cursor-pointer hover:bg-gray-50\">\r\n");
      out.write("                                            <input type=\"radio\" name=\"goal\" value=\"maintenance\" class=\"mr-3\">\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <div class=\"font-medium\">⚖️ Manter Peso</div>\r\n");
      out.write("                                                <div class=\"text-sm text-gray-600\">Equilíbrio calórico para manutenção</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label class=\"flex items-center p-3 border rounded-lg cursor-pointer hover:bg-gray-50\">\r\n");
      out.write("                                            <input type=\"radio\" name=\"goal\" value=\"muscle-gain\" class=\"mr-3\">\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <div class=\"font-medium\">💪 Ganhar Massa</div>\r\n");
      out.write("                                                <div class=\"text-sm text-gray-600\">Superávit calórico para hipertrofia</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <label class=\"block text-sm font-medium text-dark mb-2\">Peso Meta (kg)</label>\r\n");
      out.write("                                    <input type=\"number\" id=\"target-weight\" value=\"70\" step=\"0.1\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <label class=\"block text-sm font-medium text-dark mb-2\">Prazo (semanas)</label>\r\n");
      out.write("                                    <input type=\"number\" id=\"timeline\" value=\"12\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mt-8 pt-8 border-t\">\r\n");
      out.write("                        <button onclick=\"calculateGoals()\" class=\"w-full bg-primary text-white py-4 rounded-lg font-semibold hover:bg-secondary transition-colors\">\r\n");
      out.write("                            <span id=\"calc-btn-text\">🧮 Calcular Metas Personalizadas</span>\r\n");
      out.write("                            <div id=\"calc-loading\" class=\"hidden flex items-center justify-center\">\r\n");
      out.write("                                <div class=\"loading w-5 h-5 border-2 border-white border-t-transparent rounded-full mr-2\"></div>\r\n");
      out.write("                                Calculando...\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Results -->\r\n");
      out.write("                <div id=\"goal-results\" class=\"mt-8 hidden\">\r\n");
      out.write("                    <!-- Will be populated by JavaScript -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"bg-dark text-white py-12\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"grid md:grid-cols-4 gap-8\">\r\n");
      out.write("                <div class=\"md:col-span-2\">\r\n");
      out.write("                    <h3 class=\"text-2xl font-bold text-primary mb-4\">💪 FitNutri AI</h3>\r\n");
      out.write("                    <p class=\"text-gray-300 mb-4\">\r\n");
      out.write("                        Plataforma inteligente que cruza alimentação e atividade física para gerar recomendações personalizadas baseadas em suas metas de saúde.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div class=\"text-sm text-gray-400\">\r\n");
      out.write("                        <p>• 5 Servlets especializados</p>\r\n");
      out.write("                        <p>• Balanço calórico em tempo real</p>\r\n");
      out.write("                        <p>• IA Coach personalizado</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 class=\"text-lg font-semibold mb-4\">Servlets</h4>\r\n");
      out.write("                    <ul class=\"space-y-2\">\r\n");
      out.write("                        <li><a href=\"goal-setup.html\" class=\"text-gray-300 hover:text-primary transition-colors\">Goal Setup</a></li>\r\n");
      out.write("                        <li><a href=\"nutrition.html\" class=\"text-gray-300 hover:text-primary transition-colors\">Nutrition Analyzer</a></li>\r\n");
      out.write("                        <li><a href=\"activity.html\" class=\"text-gray-300 hover:text-primary transition-colors\">Activity Tracker</a></li>\r\n");
      out.write("                        <li><a href=\"balance.html\" class=\"text-gray-300 hover:text-primary transition-colors\">Balance Engine</a></li>\r\n");
      out.write("                        <li><a href=\"ai-recommendations.html\" class=\"text-gray-300 hover:text-primary transition-colors\">AI Coach</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 class=\"text-lg font-semibold mb-4\">APIs Integradas</h4>\r\n");
      out.write("                    <ul class=\"space-y-2 text-gray-300\">\r\n");
      out.write("                        <li>🥗 Edamam Food API</li>\r\n");
      out.write("                        <li>📊 USDA FoodData Central</li>\r\n");
      out.write("                        <li>🏃 Google Fit API</li>\r\n");
      out.write("                        <li>⌚ Fitbit API</li>\r\n");
      out.write("                        <li>🤖 OpenAI GPT-4 API</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"border-t border-gray-700 mt-8 pt-8 text-center\">\r\n");
      out.write("                <p class=\"text-gray-300\">&copy; 2024 FitNutri AI. Sistema completo com 5 Servlets Java integrados às principais APIs de nutrição, fitness e IA do mercado.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
